import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import CardNav from "@/components/CardNav";
import React from "react";

const outfit = Outfit( { subsets: [ 'latin' ], variable: '--font-sans' } );

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const items = [
  {
    label: 'Anime',
    links: [ { label: 'View Anime', href: '/anime' } ],
  },
  {
    label: 'Manga',
    links: [ { label: 'View Manga', href: '/manga' } ],
  },
  {
    label: 'Games',
    links: [ { label: 'View Games', href: '/games' } ],
  }
];

export default function RootLayout( {
                                      children,
                                    }: Readonly<{
  children: React.ReactNode;
}> ) {
  return (
    <html lang="en" className={ cn( outfit.className, 'dark p-4 bg-background text-foreground' ) }>
    <body className={ `antialiased` }>
    <CardNav items={ items } logo={ 'favicon.ico' } logoAlt={ 'Logo' } baseColor={ '#1c2e38' } menuColor={ '#f3e3ea' }
             buttonBgColor={ '#c67b96' } buttonTextColor={ '#f3e3ea' } ease={ 'back.out' }/>
    <div className={ 'absolute inset-0 flex flex-col gap-4 top-24 left-10' }>
      { children }
    </div>
    </body>
    </html>
  );
}